# Generated by Django 4.0.2 on 2022-03-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='createDate',
            new_name='createdDate',
        ),
    ]
